services:
  db-mascotas:
    image: postgres:17-alpine
    container_name: db-mascotas
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db_mascotas
    ports:
      - "5433:5432"
    volumes:
      - pgdata_mascotas:/var/lib/postgresql/data

  ms-mascotas:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ms-mascotas
    ports:
      - "8090:8090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-mascotas:5432/db_mascotas
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - db-mascotas
    extra_hosts:
      - "host.docker.internal:host-gateway"
volumes:
  pgdata_mascotas: