spring.application.name=servicio-gestion
spring.mvc.problemdetails.enabled=true
server.port=${APP_PORT:8081}
jwt.secret=${JWT_SECRET:secret_key}
spring.jpa.hibernate.ddl-auto=${DB_DDL_STRATEGY:create-drop}

resilience4j.retry.configs.default.max-attempts=3
resilience4j.retry.configs.default.wait-duration=2s
resilience4j.retry.configs.default.retry-exceptions[0]=java.lang.RuntimeException
resilience4j.retry.configs.default.retry-exceptions[1]=java.io.IOException
resilience4j.retry.instances.usersMicroservice.base-config=default